id: IC2342922
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T12:33:15+00:00'
last_modified: '2022-06-08T08:57:22.732454+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24034
  title: དབྱིན་བོད་ཤན་སྦྱར་གྱི་ཕྱི་རྒྱལ་གྱི་གོ་བདེའི་འགོད་གཏམ་གཅེས་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1122':
      image_group_id: I1KG24182
      title: ''
      total_pages: 228
      order: 1
      base_file: 1122.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
