id: P009147
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:25:16.277299
source_metadata:
  id: bdr:W1KG24034
  title: དབྱིན་བོད་ཤན་སྦྱར་གྱི་ཕྱི་རྒྱལ་གྱི་གོ་བདེའི་འགོད་གཏམ་གཅེས་བཏུས།
  author: ''
  volumes:
    a60384cf86ea49b2a891e5082be84816:
      image_group_id: I1KG24182
      title: ''
      volume_number: 1
      total_pages: 228
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
